- name: Rollout deployment of power monitoring script in remote servers
  tags:
    - rollout_power_monitoring
 

  block:
    - name: Copy monitoring script to remote server
      ansible.builtin.copy:
        src: /server-health-monitoring/health_check_scripts/ipmi_check.sh
        dest: /ipsec/power_check/
        owner: odennav
        group: odennav
        mode: '0755'
        force: true
      tags:
        - copy_power_script


