- name: Delete deployment of health checks in central servers
  tags:
    - remove_all_monitoring_checks
 

  block:

    - name: Delete parent directories
      ansible.builtin.file:
        path: /ipsec
        state: absent
      tags:
        - delete_all_dir

    - name: Delete cpu_check directory
      ansible.builtin.file:
        path: /ipsec/cpu_check
        state: absent
      tags:
        - delete_cpu_check_dir

    - name: Delete disk_check directory
      ansible.builtin.file:
        path: /ipsec/disk_check
        state: absent
      tags:
        - delete_disk_check_dir

    - name: Delete elk_check directory
      ansible.builtin.file:
        path: /ipsec/elk_check
        state: absent
      tags:
        - delete_elk_check_dir

    - name: Delete memory_check directory
      ansible.builtin.file:
        path: /ipsec/memory_check
        state: absent
      tags:
        - delete_memory_check_dir

    - name: Delete ntp_check directory
      ansible.builtin.file:
        path: /ipsec/ntp_check
        state: absent
      tags:
        - delete_ntp_check_dir

    - name: Delete power_check directory
      ansible.builtin.file:
        path: /ipsec/power_check
        state: absent
      tags:
        - delete_power_check_dir


   - name: Remove cronjobs in central servers
      ansible.builtin.cron:
        name: "cpu and load average monitoring"
        state: absent
      tags:
        - remove_cron_cpu_check

    - name: Remove cronjob for disk usage
      ansible.builtin.cron:
        name: "disk usage monitoring"
        state: absent
      tags:
        - remove_cron_disk_check

    - name: Remove cronjob for checking old files
      ansible.builtin.cron:
        name: "old files monitoring"
        state: absent
      tags:
        - remove_cron_old_files_check

    - name: Remove cronjob for elk status check
      ansible.builtin.cron:
        name: "elasticsearch status monitoring"
        state: absent
      tags:
        - remove_cron_elk_check

    - name: Remove cronjob for memory usage and swap check
      ansible.builtin.cron:
        name: "memory usage monitoring"
        state: absent
      tags:
        - remove_cron_memory_check

    - name: Remove cronjob for ntp status check
      ansible.builtin.cron:
        name: "ntp status monitoring"
        state: absent
      tags:
        - remove_cron_ntp_check

    - name: Remove cronjobs in central servers
      ansible.builtin.cron:
        name: "power status monitoring"
        state: absent
      tags:
        - remove_cron_power_check

    - name: Restart service cron on centos, daemon-reload to pick up config changes
      ansible.builtin.systemd_service:
        state: restarted
        daemon_reload: true
        name: crond

