- name: Rollout deployment of cpu monitoring script in remote servers
  tags:
    - rollout_cpu_monitoring
    

  block:
    - name: Copy monitoring script to remote server
      ansible.builtin.copy:
        src: /server-health-monitoring/health_check_scripts/cpu_load_avg_check.sh
        dest: /ipsec/cpu_check/
        owner: odennav
        group: odennav
        mode: '0755'
        force: true
      tags:
        - copy_cpu_script


