- name: Rollout deployment of elasticsearch status script in remote servers
  tags:
    - rollout_elk_monitoring
 

  block:
    - name: Copy monitoring script to remote server
      ansible.builtin.copy:
        src: /server-health-monitoring/health_check_scripts/elk_health_check.sh
        dest: /ipsec/elk_check/
        owner: odennav
        group: odennav
        mode: '0755'
        force: true
      tags:
        - copy_elk_script

        
